#!/bin/sh

set -e

curl -sSL -o /usr/bin/registrator https://dl.bintray.com/fkasper/XPAND/registrator_0.9.7
curl -sSL -o /etc/registrator.toml https://dl.bintray.com/fkasper/XPAND/registrator.toml
curl -sSL -o /etc/systemd/system/registrator.service https://dl.bintray.com/fkasper/XPAND/registrator.service

chmod +x /usr/bin/registrator
systemctl daemon-reload
