#!/bin/sh

set -e

wget -O /usr/bin/registrator https://dl.bintray.com/fkasper/XPAND/registrator
wget -O /usr/bin/registrator.toml https://dl.bintray.com/fkasper/XPAND/registrator.toml
wget -O /etc/systemd/system/registrator.service https://dl.bintray.com/fkasper/XPAND/registrator.service

chmod +x /usr/bin/registrator
systemctl daemon-reload
